### ISSUE TITLE
Support Linux and Mac

### ISSUE THREAD

**Issue by da-crivelli** [da-crivelli/freecad-parametric-fea#26]

**Comment by luzpaz** [comment]
Posting on the forum asking for volunteers ?

**Comment by da-crivelli** [comment]
Linux testing under [support-linux](https://github.com/da-crivelli/freecad-parametric-fea/tree/support-linux) currently failing behind poetry

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/freecad/Mod/Fem/femtools/ccxtools.py", line 41, in <module>
    from PySide import QtCore  # there might be a special reason this is not guarded ?!?
  File "/usr/lib/freecad/Ext/PySide/QtCore.py", line 1, in <module>
    from PySide2.QtCore import *
  File "/home/vscode/.cache/pypoetry/virtualenvs/freecadparametricfea-kI3Eui7x-py3.9/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ImportError: /home/vscode/.cache/pypoetry/virtualenvs/freecadparametricfea-kI3Eui7x-py3.9/lib/python3.9/site-packages/PySide2/Qt/lib/libQt5Network.so.5: undefined symbol: _ZdaPvm, version Qt_5
```

Works a bit better if packages are installed by pip, however some results don't seem to match the Windows version for some reason

```
FAILED tests/test_parametric.py::test_single_parametric - assert 0.8644717225101032 > 1.9
FAILED tests/test_parametric.py::test_parametric_material - assert 0.8661463150520748 > 1.9
FAILED tests/test_parametric.py::test_parametric_generic_obj - assert 0.4211055547016598 > 0.9
FAILED tests/test_parametric.py::test_custom_outputs - assert 0.34870476594446376 > 0.7
========== 4 failed, 9 passed in 51.06s =======
```

**Comment by luzpaz** [comment]
Any progress ?

**Comment by da-crivelli** [comment]
> Any progress ?

Not yet unfortunately, but should be able to resume development in the next couple of weeks
